<template>
  <section class="panel" :aria-label="t('dashboard.heatmap')"><header><h3>{{ t("dashboard.heatmap") }}</h3><DashboardStatusBadge :status="result.status" /></header>
    <p>{{ t("dashboard.heatmapRange") }}: {{ formatDateTime(result.from, timezone, locale) }} — {{ formatDateTime(result.to, timezone, locale) }} · {{ t("dashboard.asOf") }}: {{ formatDateTime(result.asOf, timezone, locale) }}</p>
    <template v-if="result.status !== 'unavailable'"><p v-if="result.status === 'partial'">{{ t("dashboard.knownPartialLowerBound") }} · {{ t("dashboard.readyRepos") }}: {{ result.readyRepoCount }}/{{ result.totalRepoCount }} · {{ t(`dashboard.reason.${result.partialReason}`) }} · {{ comparisonLabel }}</p><p v-else>{{ comparisonLabel }}</p><div class="heatmap" role="img" :aria-label="summary"><span v-for="day in result.data.days" :key="day.from" :style="{ opacity: `${0.14 + day.commits / maximum * .86}` }" :aria-label="`${formatDateTime(day.from, timezone, locale)}: ${day.commits}`" tabindex="0" /></div></template><p v-else>{{ t("dashboard.readyRepos") }}: {{ result.readyRepoCount }}/{{ result.totalRepoCount }} · {{ t(`dashboard.reason.${result.unavailableReason}`) }} · {{ comparisonLabel }}</p><p class="sr-only">{{ summary }}</p>
  </section>
</template>
<script setup lang="ts">
import { computed } from "vue"; import { useI18n } from "vue-i18n"; import type { DashboardData } from "@agent-workbench/shared"; import { formatComparison, formatDateTime } from "../dashboard-formatters"; import DashboardStatusBadge from "./DashboardStatusBadge.vue";
const props = defineProps<{ result: DashboardData["exceptions"]["gitHeatmap180d"]; timezone: string }>(); const { t, locale } = useI18n();
const maximum = computed(() => props.result.status === "unavailable" ? 1 : Math.max(1, ...props.result.data.days.map((day) => day.commits))); const summary = computed(() => props.result.status === "unavailable" ? t("dashboard.noData") : `${t("dashboard.heatmap")}: ${props.result.data.days.length} ${t("dashboard.days")}`); const comparisonLabel = computed(() => props.result.comparison.status === "available" ? formatComparison(props.result.comparison, locale.value) : t(`dashboard.comparison.${props.result.comparison.status}`));
</script><style scoped>.panel{background:var(--panel-bg-elevated);border:1px solid var(--border-color);border-radius:8px;padding:14px}.panel header{display:flex;justify-content:space-between}.panel h3{margin:0;font-size:14px}.panel p{font-size:12px;color:var(--text-color-secondary)}.heatmap{display:grid;grid-template-columns:repeat(30,10px);gap:3px}.heatmap span{height:10px;background:#4f8cff;border-radius:2px}.heatmap span:focus-visible{outline:2px solid #fff}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}</style>
