<template>
  <section class="panel"><header><h3>{{ t("dashboard.domainHealth") }}</h3><DashboardStatusBadge :status="result.status" /></header>
    <p>{{ t("dashboard.diagnosedAt") }}: {{ formatDateTime(result.diagnosedAt, timezone, locale) }} · {{ t("dashboard.asOf") }}: {{ formatDateTime(result.asOf, timezone, locale) }}</p>
    <p v-if="result.status === 'unavailable'">{{ t(`dashboard.reason.${result.unavailableReason}`) }} · {{ comparisonLabel }}</p>
    <template v-else><p v-if="result.status === 'partial'">{{ t(`dashboard.reason.${result.partialReason}`) }} · {{ comparisonLabel }}</p><p v-else>{{ comparisonLabel }}</p><div class="domains"><article v-for="domain in result.data" :key="domain.domain"><header><b>{{ domain.domain }}</b><DashboardStatusBadge :status="domain.status" /></header><dl><dt>{{ t("dashboard.collectionStartedAt") }}</dt><dd>{{ formatDateTime(domain.collectionStartedAt, timezone, locale) }}</dd><dt>{{ t("dashboard.reconciledThrough") }}</dt><dd>{{ formatDateTime(domain.reconciledThrough, timezone, locale) }}</dd><dt>{{ t("dashboard.rollupReadyThrough") }}</dt><dd>{{ formatDateTime(domain.rollupReadyThrough, timezone, locale) }}</dd><dt>{{ t("dashboard.retentionFloor") }}</dt><dd>{{ formatDateTime(domain.retentionFloor, timezone, locale) }}</dd><dt>{{ t("dashboard.lastSucceededAt") }}</dt><dd>{{ formatDateTime(domain.lastSucceededAt, timezone, locale) }}</dd><dt>{{ t("dashboard.generations") }}</dt><dd>{{ domain.activeGenerationCount }}/{{ domain.expectedSlotCount }}</dd><dt>{{ t("dashboard.coverageGaps") }}</dt><dd>{{ domain.coverageGaps.openCount }}/{{ domain.coverageGaps.historicalCount }} · {{ formatDateTime(domain.coverageGaps.earliestGapFrom, timezone, locale) }}</dd></dl><ul><li v-for="slot in domain.slots" :key="`${slot.producerNamespace}-${slot.producerId}-${slot.producerGeneration ?? 'missing'}`"><b>{{ slot.producerNamespace }}/{{ slot.producerId }}</b> · {{ t(`dashboard.slot.${slot.slotStatus}`) }} · {{ t(`dashboard.checkpoint.${slot.checkpoint.freshness}`) }} ({{ formatDateTime(slot.checkpoint.observedAt, timezone, locale) }}) · {{ t("dashboard.coverageGaps") }} {{ slot.coverageGaps.openCount }}/{{ slot.coverageGaps.historicalCount }}<template v-if="slot.slotStatus === 'generation_active'"> · {{ slot.producerGeneration }} · {{ t(`dashboard.lifecycle.${slot.lifecycle}`) }}</template></li></ul></article></div></template>
  </section>
</template>
<script setup lang="ts">
import { computed } from "vue"; import { useI18n } from "vue-i18n"; import type { DashboardData } from "@agent-workbench/shared"; import { formatComparison, formatDateTime } from "../dashboard-formatters"; import DashboardStatusBadge from "./DashboardStatusBadge.vue";
const props = defineProps<{ result: DashboardData["exceptions"]["domainHealth"]; timezone: string }>(); const { t, locale } = useI18n();
const comparisonLabel = computed(() => props.result.comparison.status === "available" ? formatComparison(props.result.comparison, locale.value) : t(`dashboard.comparison.${props.result.comparison.status}`));
</script><style scoped>.panel,.domains article{background:var(--panel-bg-elevated);border:1px solid var(--border-color);border-radius:8px;padding:14px}.panel>header,.domains article>header{display:flex;justify-content:space-between}.panel h3{font-size:14px;margin:0}.panel p,dt,dd,li{font-size:12px;color:var(--text-color-secondary)}.domains{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.domains dl{display:grid;grid-template-columns:auto 1fr;gap:4px 10px}.domains dd{margin:0;text-align:right}.domains ul{padding-left:16px}@media(max-width:800px){.domains{grid-template-columns:1fr}}</style>
