import type { DashboardQuerySuccessResponse, MetricResult, PanelResult } from "@agent-workbench/shared";
const comparison = { status: "available" as const, kind: "relative" as const, delta: 0.1 };
const domains = ["run"] as const;
const metric = <T>(value: T): Extract<MetricResult<T>, { status: "available" }> => ({ status: "available", value, completeness: "complete", dataIncomplete: false, requiredDomains: [...domains], comparison });
const panel = <T>(data: T): Extract<PanelResult<T>, { status: "available" }> => ({ status: "available", data, completeness: "complete", dataIncomplete: false, requiredDomains: [...domains], comparison });
const count = [{ from: 1, to: 2, count: 3 }]; const duration = [{ from: 1, to: 2, durationMs: 20 }]; const ratio = [{ from: 1, to: 2, ratio: 0.5 }];
const totalTokens = { ...metric({ count: 9 }), requiredDomains: ["model" as const], comparison: { status: "not_applicable" as const, delta: null, kind: null } };
export const dashboardSuccessFixture = {
  kind: "success", rangeId: "range-fixture", from: 1, to: 2, asOf: 2, timezone: "UTC",
  data: {
    overview: { monitoringVolume: metric({ count: 7, metricDefinitionVersion: "dashboard_collected_fact_v2", collectionConfigVersion: "config-1", configuredDomainsAtAsOf: ["run"], configurationChangedWithinRange: false }), agentDuration: metric(20), modelRequests: metric(3), modelSuccessRate: metric({ ratio: 0.5 }), cacheHitRate: metric({ ratio: null }), totalTokens },
    overviewTrends: { monitoringVolume: panel([{ from: 1, to: 2, total: 7, run: 1, session: 1, message: 1, tool: 1, execution: 1, model: 1, worker: 1 }]), agentDuration: panel(duration), modelRequests: panel([{ from: 1, to: 2, completed: 2, failed: 1, timedOut: 0, other: 0 }]), modelSuccessRate: panel(ratio), cacheHitRate: panel(ratio), totalTokens: panel([{ from: 1, to: 2, count: 9 }]) },
    agent: { metrics: { totalDuration: metric(20), runCount: metric(3), primaryRunCount: metric(2), subtaskRunCount: metric(1), userMessageCount: metric(1), assistantMessageCount: metric(2), toolCallCount: metric(2), toolSuccessRate: metric({ ratio: 1 }), manualCompactionCount: metric(0), autoCompactionCount: metric(0) }, trends: { totalDuration: panel(duration), runCount: panel(count), primaryRunCount: panel(count), subtaskRunCount: panel(count), userMessageCount: panel(count), assistantMessageCount: panel(count), toolCallCount: panel(count), toolSuccessRate: panel(ratio), manualCompactionCount: panel(count), autoCompactionCount: panel(count) }, runTerminalDistribution: panel({ all: [{ status: "completed" as const, count: 3 }], main: [{ status: "completed" as const, count: 2 }], subtask: [{ status: "completed" as const, count: 1 }] }), runTypeDistribution: panel([{ kind: "primary" as const, count: 2 }]), messageTypeDistribution: panel([{ type: "assistant" as const, count: 2 }]), toolStatusDistribution: panel([{ status: "completed" as const, count: 2 }]), toolDetails: panel([{ toolName: "read", calls: 2, completed: 2, failed: 0, cancelled: 0, unknown: 0, completedAverageDurationMs: 10 }]) },
    model: { metrics: { requestCount: metric(3), successRate: metric({ ratio: .5 }), timeoutRate: metric({ ratio: 0 }), timeoutKindBreakdown: metric({ idle: 0, total: 0, none: 3 }), completedAverageDuration: metric({ durationMs: 20, reliableSampleCount: 2 }), inputTokens: metric({ count: 4 }), outputTokens: metric({ count: 5 }), totalTokens, cacheReadTokens: metric({ count: 0 }), inputReportedCount: metric(3), outputReportedCount: metric(3), totalReportedCount: metric(3), totalDerivedCount: metric(0), cacheComparableCount: metric(3), inputTokenCoverage: metric({ ratio: 1 }), outputTokenCoverage: metric({ ratio: 1 }), totalTokenCoverage: metric({ ratio: 1 }), inputCacheCoverage: metric({ ratio: 1 }) }, trends: { requests: panel([{ from: 1, to: 2, completed: 2, failed: 1, timedOut: 0, other: 0 }]), successRate: panel(ratio), timeoutRate: panel(ratio), completedAverageDuration: panel([{ from: 1, to: 2, durationMs: 20, reliableSampleCount: 2 }]), tokens: panel([{ from: 1, to: 2, inputTokens: 4, outputTokens: 5 }]), cacheHitRate: panel(ratio) }, byModel: panel([{ provider: "p", model: "m", requests: 3, successRate: .5, timeoutRate: 0, completedAverageDurationMs: 20, reliableDurationSampleCount: 2, inputTokens: 4, outputTokens: 5, totalTokens: 9, cacheReadTokens: 0, cacheHitRate: 0 }]) },
    worker: { metrics: { unexpectedExits: metric(0), restartAttempts: metric(0), restartSucceeded: metric(0), restartFailed: metric(0) }, eventTrend: panel([{ from: 1, to: 2, unexpectedExits: 0, restartAttempts: 0 }]), restartRecords: panel([{ occurredAt: 2, event: "restart_succeeded" as const, restartStatus: "recovered" as const }]) },
    exceptions: { workerLiveSnapshot: { ...metric({ running: 1, queued: 0, concurrency: 2, utilization: .5, localFallbackRunning: 0, lastReadyAt: 2 }), snapshotAt: 2, asOf: 2 }, domainHealth: { ...panel([{ domain: "run" as const, status: "healthy" as const, collectionStartedAt: 1, reconciledThrough: 2, rollupReadyThrough: 2, retentionFloor: 1, lastSucceededAt: 2, expectedSlotCount: 1, activeGenerationCount: 1, slots: [{ slotStatus: "generation_active" as const, producerNamespace: "api", producerId: "a", producerGeneration: "g", lifecycle: "registered" as const, checkpoint: { freshness: "fresh" as const, observedAt: 2 }, coverageGaps: { openCount: 0, historicalCount: 0, earliestGapFrom: null, hasOpenGap: false } }], coverageGaps: { openCount: 0, historicalCount: 0, earliestGapFrom: null, hasOpenGap: false } }]), diagnosedAt: 2, asOf: 2 } },
  },
} satisfies DashboardQuerySuccessResponse;
