import assert from "node:assert/strict";
import test from "node:test";
import type { DashboardQuerySuccessResponse } from "@agent-workbench/shared";
import { dashboardSuccessFixture } from "./dashboard-fixture";
import { createDashboardState } from "./dashboard-state";

function responseRangeId(state: ReturnType<typeof createDashboardState>) { return state.response.value?.rangeId; }
function responseTimezone(state: ReturnType<typeof createDashboardState>) { return state.response.value?.timezone; }
function response(rangeId: string, overrides: Partial<DashboardQuerySuccessResponse> = {}): DashboardQuerySuccessResponse { return { ...dashboardSuccessFixture, rangeId, ...overrides }; }
test("默认使用 preset_7d，首次刷新只发出一个 POST", async () => { const requests: unknown[] = []; const state = createDashboardState(async (request) => { requests.push(request); return response("range-1"); }); await state.refresh(); assert.deepEqual(requests, [{ rangeKind: "preset_7d", timezone: state.timezone.value }]); assert.equal(responseRangeId(state), "range-1"); });
test("preset/timezone 自动单次刷新并以本地 sequence 丢弃旧响应", async () => { let resolveOld!: (value: DashboardQuerySuccessResponse) => void; const old = new Promise<DashboardQuerySuccessResponse>((resolve) => { resolveOld = resolve; }); const requests: string[] = []; const state = createDashboardState((request) => { requests.push(request.rangeKind); return requests.length === 1 ? old : Promise.resolve(response(`range-${requests.length}`, { timezone: request.timezone })); }); const pending = state.refresh(); state.setRangeKind("preset_30d"); assert.equal(state.response.value, null); assert.equal(state.stale.value, false); await new Promise((resolve) => setImmediate(resolve)); assert.equal(requests.length, 2); assert.equal(responseRangeId(state), "range-2"); resolveOld(response("old-range")); await pending; assert.equal(responseRangeId(state), "range-2"); state.setTimezone("Asia/Tokyo"); await new Promise((resolve) => setImmediate(resolve)); assert.equal(requests.length, 3); assert.equal(responseTimezone(state), "Asia/Tokyo"); });
test("custom 编辑不请求，Apply 恰好一次且旧响应不能覆盖", async () => { let firstResolve!: (value: DashboardQuerySuccessResponse) => void; const first = new Promise<DashboardQuerySuccessResponse>((resolve) => { firstResolve = resolve; }); let calls = 0; const state = createDashboardState((request) => { if (++calls === 1) return first; return Promise.resolve(response("new-range", { timezone: request.timezone, from: request.rangeKind === "custom" ? request.from : 1, to: request.rangeKind === "custom" ? request.to : 2 })); }); const pending = state.refresh(); state.setRangeKind("custom"); state.setCustomInput("from", "2024-01-01T00:00"); state.setCustomInput("to", "2024-01-02T00:00"); assert.equal(calls, 1); await state.refresh(); assert.equal(calls, 2); firstResolve(response("old-range")); await pending; assert.equal(responseRangeId(state), "new-range"); });
test("无效 custom 不发请求，展示受控本地错误", async () => { let calls = 0; const state = createDashboardState(async () => { calls++; return response("unexpected"); }); state.setRangeKind("custom"); state.setCustomInput("from", "2024-01-02T00:00"); state.setCustomInput("to", "2024-01-01T00:00"); await state.refresh(); assert.equal(calls, 0); assert.equal(state.errorCode.value, "CUSTOM_RANGE_ORDER"); });
